
title = ""
baseURL = "https://www.homik.de"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Software Developer. BigData and streaming Enthusiast. Spring Fan."
  facebook = ""
  twitter = "https://twitter.com/majaX1"
  instagram = ""
  youtube = ""
  github = "https://github.com/mhomik"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/mhomik/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
  disqusShortname = "majaX1"
